// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum ElevationToken: String, CaseIterable, Identifiable, Sendable {
    case flat
    case subtle
    case raised
    case floating

    public var id: String { rawValue }
}