// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum GridToken: String, CaseIterable, Identifiable, Sendable {
    case sidebar
    case browser
    case content
    case inspector
    case settings
    case dashboard
    case editor

    public var id: String { rawValue }
}