// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum IconToken: String, CaseIterable, Identifiable, Sendable {
    case navigationPrimary
    case navigationSecondary
    case utility
    case statusInfo
    case statusSuccess
    case statusWarning
    case statusDanger
    case accentAction
    case contentStructure
    case dataSeries

    public var id: String { rawValue }
}