// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum MaterialToken: String, CaseIterable, Identifiable, Sendable {
    case shell
    case sidebar
    case titlebar
    case toolbar
    case workspace
    case grouped
    case raised
    case panel
    case card
    case inset
    case input
    case code
    case menu
    case hover
    case pressed
    case selected
    case notice
    case tableHeader
    case tableRow
    case popover
    case modal
    case drawer
    case overlay
    case scrim

    public var id: String { rawValue }
}