// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum MotionCurveToken: String, CaseIterable, Identifiable, Sendable {
    case standard
    case emphasized
    case snappy
    case settle
    case modal
    case reduced

    public var id: String { rawValue }
}