// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum MotionToken: String, CaseIterable, Identifiable, Sendable {
    case quick
    case regular
    case emphasis
    case hover
    case selection
    case modalPresence

    public var id: String { rawValue }
}