// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum RadiusToken: String, CaseIterable, Identifiable, Sendable {
    case small
    case medium
    case large
    case extraLarge
    case pill

    public var id: String { rawValue }
}