// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum ShadowToken: String, CaseIterable, Identifiable, Sendable {
    case flat
    case hairline
    case subtle
    case raised
    case floating
    case focus

    public var id: String { rawValue }
}