// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum SpacingToken: String, CaseIterable, Identifiable, Sendable {
    case xxxs
    case xxs
    case xs
    case sm
    case md
    case lg
    case xl
    case xxl
    case sidebarInset
    case rowGap
    case panelPadding
    case composerPadding
    case toolbarHeight
    case contentGutter

    public var id: String { rawValue }
}