// Generated by BuilderArtifactGenerator. Do not edit by hand.

public enum TypographyToken: String, CaseIterable, Identifiable, Sendable {
    case displayLarge
    case display
    case displaySmall
    case hero
    case pageTitle
    case title
    case titleCompact
    case sectionTitle
    case sectionSubtitle
    case eyebrow
    case bodyLarge
    case body
    case bodyStrong
    case bodySmall
    case bodySmallStrong
    case label
    case labelStrong
    case caption
    case captionStrong
    case helper
    case buttonLarge
    case button
    case buttonSmall
    case mono
    case monoSmall
    case monoCaption
    case numeric
    case tableMeta

    public var id: String { rawValue }
}